spring.application.name=cloud-app

spring.datasource.url=jdbc:mysql://cst-323-db.mysql.database.azure.com/rpg_characters
spring.datasource.username=cst323admin
spring.datasource.password=Ailberty7!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true