package com.gcu.models;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * CharacterEntity represents a character created by a user in the application. It contains fields for character attributes such as name, level, gender, type, description, and an image URL.
 * It also includes metadata fields for visibility, flagged status, and timestamps for creation and updates. 
 * The entity is linked to a UserEntity (the creator), a RaceEntity (the character
 */
@Entity
@Table(name = "characters")
public class CharacterEntity
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "character_id")
    private Integer characterId;

    @Column(name = "character_name", nullable = false)
    private String characterName;

    @Column(name = "character_level", nullable = false)
    private Integer characterLevel;

    @Column(name = "character_gender", nullable = false)
    private String characterGender;

    @Column(name = "character_type", nullable = false)
    private String characterType;

    @Column(name = "character_description", columnDefinition = "TEXT")
    private String characterDescription;

    @Column(name = "image_url", columnDefinition = "TEXT")
    private String imageUrl;

    @Column(name = "visibility", nullable = false)
    private Integer visibility;

    @Column(name = "flagged", nullable = false)
    private Boolean flagged = false;

    @Column(name = "created_on")
    private LocalDateTime createdOn;

    @Column(name = "updated_on")
    private LocalDateTime updatedOn;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private UserEntity user;

    @ManyToOne
    @JoinColumn(name = "race_id", nullable = false)
    private RaceEntity race;

    @ManyToOne
    @JoinColumn(name = "class_id", nullable = false)
    private ClassEntity characterClass; 

    /**
     * Default constructor for CharacterEntity. Required by JPA for entity instantiation.
     */
    public CharacterEntity()
    {
    }

    /**
     * Gets the unique identifier for the character.
     * @return the characterId
     */
    public Integer getCharacterId()
    {
        return characterId;
    }

    /**
     * Sets the unique identifier for the character. This is typically auto-generated by the database.
     * @param characterId the characterId to set
     */
    public void setCharacterId(Integer characterId)
    {
        this.characterId = characterId;
    }

    /**
     * Gets the visibility status of the character. This field can be used to determine if the character is public or private.
     * @return the visibility
     */
    public Integer getVisibility()
    {
        return visibility;
    }

    /**
     * Sets the visibility status of the character. This field can be used to determine if the character is public or private.
     * @param visibility the visibility to set
     */
    public void setVisibility(Integer visibility)
    {
        this.visibility = visibility;
    }

    /**
     * Gets the flagged status of the character. This field can be used to indicate if the character has been flagged for review or inappropriate content.
     * @return the flagged status
     */
    public Boolean getFlagged()
    {
        return flagged;
    }

    /**
     * Sets the flagged status of the character. This field can be used to indicate if the character has been flagged for review or inappropriate content.
     * @param flagged the flagged status to set
     */
    public void setFlagged(Boolean flagged)
    {
        this.flagged = flagged;
    }

    /**
     * Gets the name of the character.
     * @return the character name
     */
    public String getCharacterName()
    {
        return characterName;
    }

    /**
     * Sets the name of the character.
     * @param characterName the character name to set
     */
    public void setCharacterName(String characterName)
    {
        this.characterName = characterName;
    }

    /**
     * Gets the level of the character.
     * @return the character level
     */
    public Integer getCharacterLevel()
    {
        return characterLevel;
    }

    /**
     * Sets the level of the character.
     * @param characterLevel the character level to set
     */
    public void setCharacterLevel(Integer characterLevel)
    {
        this.characterLevel = characterLevel;
    }

    /**
     * Gets the gender of the character.
     * @return the character gender
     */
    public String getCharacterGender()
    {
        return characterGender;
    }

    /**
     * Sets the gender of the character.
     * @param characterGender the character gender to set
     */
    public void setCharacterGender(String characterGender)
    {
        this.characterGender = characterGender;
    }

    /** 
     * Gets the description of the character. This field can contain a detailed backstory or information about the character's personality, traits, and history.
     * @return the character description 
     */
    public String getCharacterDescription()
    {
        return characterDescription;
    }

    /**
     * Sets the description of the character. This field can contain a detailed backstory or information about the character's personality, traits, and history.
     * @param characterDescription the character description to set
     */
    public void setCharacterDescription(String characterDescription)
    {
        this.characterDescription = characterDescription;
    }

    /**
     * Gets the type of the character. This field can be used to categorize characters into different types or archetypes (e.g., player, monster, NPC).
     * @return the character type
     */
    public String getCharacterType()
    {
        return characterType;
    }

    /**
     * Sets the type of the character. This field can be used to categorize characters into different types or archetypes (e.g., player, monster, NPC).
     * @param characterType the character type to set
     */
    public void setCharacterType(String characterType)
    {
        this.characterType = characterType;
    }

    /**
     * Gets the user who created the character. This is a many-to-one relationship, as one user can create multiple characters.
     * @return the user who created the character
     */
    public UserEntity getUser()
    {
        return user;
    }

    /**
     * Sets the user who created the character. This is a many-to-one relationship, as one user can create multiple characters.
     * @param user the user to set as the creator of the character
     */
    public void setUser(UserEntity user)
    {
        this.user = user;
    }
    
    /**
     * Gets the race of the character. This is a many-to-one relationship, as one race can be associated with multiple characters.
     * @return the race of the character
     */
    public RaceEntity getRace()
    {
        return race;
    }

    /**
     *  Sets the race of the character. This is a many-to-one relationship, as one race can be associated with multiple characters.
     * @param race the race to set for the character
     */
    public void setRace(RaceEntity race)
    {
        this.race = race;
    }
   
    /**
     * Gets the class of the character. This is a many-to-one relationship, as one class can be associated with multiple characters.
     * @return the class of the character
     */
    public ClassEntity getCharacterClass()
    {
        return characterClass;
    }
    
    /**
     * Sets the class of the character. This is a many-to-one relationship, as one class can be associated with multiple characters.
     * @param characterClass the class to set for the character
     */
    public void setCharacterClass(ClassEntity characterClass)
    {
        this.characterClass = characterClass;
    }

    /**
     * Gets the image URL for the character. This field can be used to store a link to an image representing the character, such as an avatar or portrait.
     * @return the image URL for the character
     */
    public String getImageUrl()
    {
        return imageUrl;
    }
 
    /**
     * Sets the image URL for the character. This field can be used to store a link to an image representing the character, such as an avatar or portrait.
     * @param imageUrl the image URL to set for the character
     */
    public void setImageUrl(String imageUrl)
    {
        this.imageUrl = imageUrl;
    }
    
    /**
     * Gets the creation timestamp for the character. This field can be used to track when the character was created in the system.
     * @return the creation timestamp for the character
     */
    public LocalDateTime getCreatedAt()
    {
        return createdOn;
    }
    
    /**
     * Sets the creation timestamp for the character. This field can be used to track when the character was created in the system.
     * @param createdOn the creation timestamp to set for the character
     */
    public void setCreatedAt(LocalDateTime createdOn)
    {
        this.createdOn = createdOn;
    }
    
    /**
     * Gets the last updated timestamp for the character. This field can be used to track when the character was last modified in the system.
     * @return the last updated timestamp for the character
     */
    public LocalDateTime getUpdatedAt()
    {
        return updatedOn;
    }
    
    /**
     * Sets the last updated timestamp for the character. This field can be used to track when the character was last modified in the system.
     * @param updatedOn the last updated timestamp to set for the character
     */
    public void setUpdatedAt(LocalDateTime updatedOn)
    {
        this.updatedOn = updatedOn;
    }

}