package com.gcu.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * UserEntity represents a user of the application. It contains fields for user attributes such as username, password, and role.
 * The username is unique to prevent duplicate entries in the database. The role field can be used
 * to differentiate between regular users and administrators, allowing for role-based access control within the application.
 */
@Entity
@Table(name = "users")
public class UserEntity
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id")
    private Integer userId;

    @Column(name = "username", nullable = false, unique = true)
    private String username;

    @Column(name = "password", nullable = false)
    private String password;

    @Column(name = "role", nullable = false)
    private String role;

    /**
     * Default constructor for UserEntity. This is required by JPA for entity instantiation. It allows the framework to create instances of UserEntity when retrieving data from the database.
     */
    public UserEntity()
    {
    }

    /**
     * Gets the user ID of the user. This is the primary key for the UserEntity and is generated automatically by the database.
     * @return the user ID of the user
     */
    public Integer getUserId()
    {
        return userId;
    }

    /**
     * Sets the user ID of the user. This method is typically not used directly, as the user ID is generated by the database when a new user is created. However, it can be useful for testing or when manually setting the ID for some reason.
     * @param userId the user ID to set for the user
     */
    public void setUserId(Integer userId)
    {
        this.userId = userId;
    }

    /**
     * Gets the username of the user. The username is a unique identifier for the user and is used for authentication purposes.
     * @return the username of the user
     */
    public String getUsername()
    {
        return username;
    }

    /**
     * Sets the username of the user. The username must be unique across all users in the database to prevent conflicts during authentication. This method should be used with caution, as changing a username can affect user access and authentication.
     * @param username the username to set for the user. It should be unique and not null.
     */
    public void setUsername(String username)
    {
        this.username = username;
    }

    /**
     * Gets the password of the user. The password is used for authentication purposes and should be stored securely (e.g., hashed) in a real application.
     * @return the password of the user
     */
    public String getPassword()
    {
        return password;
    }

    /**
     * Sets the password of the user. The password should be stored securely (e.g., hashed) in a real application to protect user credentials. This method should be used with caution, as changing a password can affect user access and authentication.
     * @param password the password to set for the user. It should not be null and should meet any security requirements (e.g., minimum length, complexity).
     */
    public void setPassword(String password)
    {
        this.password = password;
    }

    /**
     * Gets the role of the user. The role can be used to differentiate between regular users and administrators, allowing for role-based access control within the application.
     * @return the role of the user
     */
    public String getRole()
    {
        return role;
    }

    /**
     * Sets the role of the user. The role can be used to differentiate between regular users and administrators, allowing for role-based access control within the application. This method should be used with caution, as changing a user's role can affect their access permissions within the application.
     * @param role the role to set for the user. It should not be null and should be a valid role defined in the application (e.g., "USER", "ADMIN").
     */
    public void setRole(String role)
    {
        this.role = role;
    }
}